import { test } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/')
  await page.goto('http://localhost:8080/#/')
  await page.getByRole('link', { name: ' Sign in' }).click()
  await page.getByRole('link', { name: 'Need an account?' }).click()
  await page.getByRole('link', { name: ' Sign in' }).click()
  await page.getByPlaceholder('Email').click()
  await page.getByPlaceholder('Email').fill('alexandre_bartie@hotmail.com')
  await page.getByPlaceholder('Password').click()
  await page.getByPlaceholder('Password').fill('1234567890')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByRole('link', { name: 'Alexandre Silva' }).click()
  await page.getByRole('link', { name: 'Favorited Articles' }).click()
  await page.getByRole('link', { name: 'My Articles' }).click()
  await page.getByRole('link', { name: ' Edit Profile Settings' }).click()
  await page.getByPlaceholder('Short bio about you').click()
  await page.getByPlaceholder('Short bio about you').fill('Good professional')
  await page.getByRole('button', { name: 'Update Settings' }).click()
  await page.getByPlaceholder('Password').click()
  await page.getByPlaceholder('Password').fill('1234567890')
  await page.getByRole('button', { name: 'Update Settings' }).click()
  await page.getByRole('button', { name: 'Update Settings' }).click()
  await page.getByRole('button', { name: 'Or click here to logout.' }).click()
})
